# Use containerized trusty
dist: trusty
sudo: false

# Configure ruby versions
language: ruby
rvm: 
  - 2.3.6
  - 2.4.3
  - 2.5.0

# Use latest PostgreSQL
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

# Get rid of encrypted .env which it can't read
before_install: 
  - gem update --system
  - mv .env .env.encrypted

# Lint codebase after successful spec run
after_script:
  - bundle exec rubocop

